### ISSUE TITLE
korrekte Responses in Controllern implementieren

### ISSUE THREAD

**Issue by thuascgn** [zvaehn/WBA2SS15SchifferRoseHowe#11]
Resourcen Controller müssen anhand von ResponseHelper so wohldefiniert wie möglich antworten

**Comment by zvaehn** [comment]
ich sehe persönlich und in der Hinsicht auf die Dienstnehmer Applikation keinerlei Nutzen des erweiterten responses.

status, code und message sind vollkommen ausreichend.

Es interessiert nur: ist ein Fehler passiert, ja oder nein. Wenn ja, dann gib die Meldung aus und gut ist.
