### ISSUE TITLE
Fix the http.req put request

### ISSUE THREAD

**Issue by zvaehn** [zvaehn/WBA2SS15SchifferRoseHowe#22]

**Comment by NRose** [comment]
nach vielen Stunden Arbeit, endlich gefixt! 
________________________
var putData        = {
          "offers": req.body.offers 
};
HTTP Request konnte nicht ausgeführt werden("Socket hang up"), weil die zu bearbeiteten Daten für die Offers nur aus den Values bestand, nicht aber aus dem Key "offers".
________________________

'Content-Length': Buffer.byteLength(JSON.stringify(putData)) 

zusätzlich drauf geachtet werden muss auch das die Content-Length richtig berechnet werden muss.
